### ISSUE TITLE
 Cambio en tabla de factores para cálculo de la prima

### ISSUE THREAD

**Issue by cmonsalvec** [AxleJouberth317/CalculoPrimaV1#2]
Estimados,

De acuerdo a las estadísticas del 2019 hemos comprobado que la siniestralidad de conductores de 65 años de edad o más ha aumentado. Por tal razón el directorio de nuestra empresa ha decidido modificar para este rango de edad el número de puntos que puede perder en su licencia de conducir. El directorio ha aprobado que ese número de puntos pase de 5 a 4.

Por favor realizar los cambios en el sistema para que esta nueva disposición del directorio pueda entrar en funcionamiento.

**Comment by AxleJouberth317** [comment]
Se ha llevado a cabo la reproducción del incidente donde se ha comprobado que el número de puntos que puede perder en la licencia de conducir para conductores de 65 años o más es actualmente de 5 puntos, y difiere del valor a ser cambiado de 4 puntos.

`else if( 65 <= edad && edad <=90 ) v = 5;` 
donde v es el número del puntos que puede perder

Se llevará a cabo el análisis de impacto y categorizar por otro miembro del equipo

**Comment by Angeluz-07** [comment]
Después de un análisis. Consideramos que este cambio afectará a los componentes : 
- Web
- Administrador
- Cliente
- Movil

**Comment by anthoHerrera** [comment]
Ya he resuelto el problema, se actualizado la forma de calcular prima https://github.com/AxleJouberth317/CalculoPrimaV1/commit/33fd92f1663d2974a33f140bb6c3a9d649f5bd9b

**Comment by AxleJouberth317** [comment]
Se han realizado las pruebas del sistema con éxito luego del cambio, la documentación se encuentra en el siguiente enlace [https://docs.google.com/document/d/1MBxmkqmv1ptgoVeI6PUQ1MRupJMduBZpKDKGzskegFY/edit?usp=sharing](url)

**Comment by AxleJouberth317** [comment]
Estimado @cmonsalvec, se han realizado las pruebas con éxito luego de realizar los cambios en la tabla de factores. Esperamos su validación respecto a los cambios solicitados.

**Comment by cmonsalvec** [comment]
He revisado lo realizado por ustedes, estoy conforme con las pruebas, por lo tanto por favor poner en funcionamiento el cambio para poder proceder con el cierre de este ticket
